// Package contractor - (version: "0.1") - Automatically generated by cinp-codegen from /api/v1/Proxmox/ at 2026-01-08T06:07:57.779085+00:00
package contractor

import (
	"context"
	"fmt"
	cinp "github.com/cinp/go"
	"reflect"
	"strings"
	"time"
)

// ProxmoxProxmoxComplex - Model ProxmoxComplex(/api/v1/Proxmox/ProxmoxComplex)
/*
ProxmoxComplex(name, site, description, built_percentage, updated, created, complex_ptr, proxmox_host, proxmox_username, proxmox_password)
*/
type ProxmoxProxmoxComplex struct {
	cinp.BaseObject
	cinp            cinp.CInPClient `json:"-"`
	Name            *string         `json:"name,omitempty"`
	Site            *string         `json:"site,omitempty"`
	Description     *string         `json:"description,omitempty"`
	BuiltPercentage *int            `json:"built_percentage,omitempty"`
	Updated         *time.Time      `json:"updated,omitempty"`
	Created         *time.Time      `json:"created,omitempty"`
	ProxmoxHost     *string         `json:"proxmox_host,omitempty"`
	ProxmoxUsername *string         `json:"proxmox_username,omitempty"`
	ProxmoxPassword *string         `json:"proxmox_password,omitempty"`
	Members         *[]string       `json:"members,omitempty"`
	State           *string         `json:"state,omitempty"`
	Type            *string         `json:"type,omitempty"`
}

// ProxmoxProxmoxComplexNew - Make a new object of Model ProxmoxComplex
func (service *Contractor) ProxmoxProxmoxComplexNew() *ProxmoxProxmoxComplex {
	return &ProxmoxProxmoxComplex{cinp: service.cinp}
}

// ProxmoxProxmoxComplexNewWithID - Make a new object of Model ProxmoxComplex
func (service *Contractor) ProxmoxProxmoxComplexNewWithID(id string) *ProxmoxProxmoxComplex {
	result := ProxmoxProxmoxComplex{cinp: service.cinp}
	result.SetURI("/api/v1/Proxmox/ProxmoxComplex:" + id + ":")
	return &result
}

// ProxmoxProxmoxComplexGet - Get function for Model ProxmoxComplex
func (service *Contractor) ProxmoxProxmoxComplexGet(ctx context.Context, id string) (*ProxmoxProxmoxComplex, error) {
	object, err := service.cinp.Get(ctx, "/api/v1/Proxmox/ProxmoxComplex:"+id+":")
	if err != nil {
		return nil, err
	}
	result := (*object).(*ProxmoxProxmoxComplex)
	result.cinp = service.cinp

	return result, nil
}

// ProxmoxProxmoxComplexGetURI - Get function for Model ProxmoxComplex vi URI
func (service *Contractor) ProxmoxProxmoxComplexGetURI(ctx context.Context, uri string) (*ProxmoxProxmoxComplex, error) {
	if !strings.HasPrefix(uri, "/api/v1/Proxmox/ProxmoxComplex:") {
		return nil, fmt.Errorf("URI is not for a 'ProxmoxProxmoxComplex'")
	}

	object, err := service.cinp.Get(ctx, uri)
	if err != nil {
		return nil, err
	}
	result := (*object).(*ProxmoxProxmoxComplex)
	result.cinp = service.cinp

	return result, nil
}

// Create - Create function for Model ProxmoxComplex
// NOTE: the object will be updated with values from the server
func (object *ProxmoxProxmoxComplex) Create(ctx context.Context) error {
	err := object.cinp.Create(ctx, "/api/v1/Proxmox/ProxmoxComplex", object)
	if err != nil {
		return err
	}

	return nil
}

// Update - Update function for Model ProxmoxComplex
// NOTE: the object will be updated with values from the server
func (object *ProxmoxProxmoxComplex) Update(ctx context.Context) error {
	err := object.cinp.Update(ctx, object)
	if err != nil {
		return err
	}

	return nil
}

// Delete - Delete function for Model ProxmoxComplex
func (object *ProxmoxProxmoxComplex) Delete(ctx context.Context) error {
	if err := object.cinp.Delete(ctx, object); err != nil {
		return err
	}

	return nil
}

// ProxmoxProxmoxComplexListFilters - Return a slice of valid filter names ProxmoxComplex
func (service *Contractor) ProxmoxProxmoxComplexListFilters() [0]string {
	return [0]string{}
}

// ProxmoxProxmoxComplexList - List function for Model ProxmoxComplex
func (service *Contractor) ProxmoxProxmoxComplexList(ctx context.Context, filterName string, filterValues map[string]interface{}) (<-chan *ProxmoxProxmoxComplex, error) {
	if filterName != "" {
		for _, item := range service.ProxmoxProxmoxComplexListFilters() {
			if item == filterName {
				goto good
			}
		}
		return nil, fmt.Errorf("filter '%s' is invalid", filterName)
	}
good:

	in := service.cinp.ListObjects(ctx, "/api/v1/Proxmox/ProxmoxComplex", reflect.TypeOf(ProxmoxProxmoxComplex{}), filterName, filterValues, 50)
	out := make(chan *ProxmoxProxmoxComplex)
	go func() {
		defer close(out)
		for v := range in {
			(*v).(*ProxmoxProxmoxComplex).cinp = service.cinp
			out <- (*v).(*ProxmoxProxmoxComplex)
		}
	}()
	return out, nil
}

// ProxmoxProxmoxFoundation - Model ProxmoxFoundation(/api/v1/Proxmox/ProxmoxFoundation)
/*
ProxmoxFoundation(locator, site, blueprint, id_map, located_at, built_at, updated, created, foundation_ptr, proxmox_complex, proxmox_id)
*/
type ProxmoxProxmoxFoundation struct {
	cinp.BaseObject
	cinp           cinp.CInPClient `json:"-"`
	Locator        *string         `json:"locator,omitempty"`
	Site           *string         `json:"site,omitempty"`
	Blueprint      *string         `json:"blueprint,omitempty"`
	IDMap          *string         `json:"id_map,omitempty"`
	LocatedAt      *time.Time      `json:"located_at,omitempty"`
	BuiltAt        *time.Time      `json:"built_at,omitempty"`
	Updated        *time.Time      `json:"updated,omitempty"`
	Created        *time.Time      `json:"created,omitempty"`
	ProxmoxComplex *string         `json:"proxmox_complex,omitempty"`
	ProxmoxID      *int            `json:"proxmox_id,omitempty"`
	State          *string         `json:"state,omitempty"`
	Type           *string         `json:"type,omitempty"`
	ClassList      *string         `json:"class_list,omitempty"`
}

// ProxmoxProxmoxFoundationNew - Make a new object of Model ProxmoxFoundation
func (service *Contractor) ProxmoxProxmoxFoundationNew() *ProxmoxProxmoxFoundation {
	return &ProxmoxProxmoxFoundation{cinp: service.cinp}
}

// ProxmoxProxmoxFoundationNewWithID - Make a new object of Model ProxmoxFoundation
func (service *Contractor) ProxmoxProxmoxFoundationNewWithID(id string) *ProxmoxProxmoxFoundation {
	result := ProxmoxProxmoxFoundation{cinp: service.cinp}
	result.SetURI("/api/v1/Proxmox/ProxmoxFoundation:" + id + ":")
	return &result
}

// ProxmoxProxmoxFoundationGet - Get function for Model ProxmoxFoundation
func (service *Contractor) ProxmoxProxmoxFoundationGet(ctx context.Context, id string) (*ProxmoxProxmoxFoundation, error) {
	object, err := service.cinp.Get(ctx, "/api/v1/Proxmox/ProxmoxFoundation:"+id+":")
	if err != nil {
		return nil, err
	}
	result := (*object).(*ProxmoxProxmoxFoundation)
	result.cinp = service.cinp

	return result, nil
}

// ProxmoxProxmoxFoundationGetURI - Get function for Model ProxmoxFoundation vi URI
func (service *Contractor) ProxmoxProxmoxFoundationGetURI(ctx context.Context, uri string) (*ProxmoxProxmoxFoundation, error) {
	if !strings.HasPrefix(uri, "/api/v1/Proxmox/ProxmoxFoundation:") {
		return nil, fmt.Errorf("URI is not for a 'ProxmoxProxmoxFoundation'")
	}

	object, err := service.cinp.Get(ctx, uri)
	if err != nil {
		return nil, err
	}
	result := (*object).(*ProxmoxProxmoxFoundation)
	result.cinp = service.cinp

	return result, nil
}

// Create - Create function for Model ProxmoxFoundation
// NOTE: the object will be updated with values from the server
func (object *ProxmoxProxmoxFoundation) Create(ctx context.Context) error {
	err := object.cinp.Create(ctx, "/api/v1/Proxmox/ProxmoxFoundation", object)
	if err != nil {
		return err
	}

	return nil
}

// Update - Update function for Model ProxmoxFoundation
// NOTE: the object will be updated with values from the server
func (object *ProxmoxProxmoxFoundation) Update(ctx context.Context) error {
	err := object.cinp.Update(ctx, object)
	if err != nil {
		return err
	}

	return nil
}

// Delete - Delete function for Model ProxmoxFoundation
func (object *ProxmoxProxmoxFoundation) Delete(ctx context.Context) error {
	if err := object.cinp.Delete(ctx, object); err != nil {
		return err
	}

	return nil
}

// ProxmoxProxmoxFoundationListFilters - Return a slice of valid filter names ProxmoxFoundation
func (service *Contractor) ProxmoxProxmoxFoundationListFilters() [1]string {
	return [1]string{"site"}
}

// ProxmoxProxmoxFoundationList - List function for Model ProxmoxFoundation
func (service *Contractor) ProxmoxProxmoxFoundationList(ctx context.Context, filterName string, filterValues map[string]interface{}) (<-chan *ProxmoxProxmoxFoundation, error) {
	if filterName != "" {
		for _, item := range service.ProxmoxProxmoxFoundationListFilters() {
			if item == filterName {
				goto good
			}
		}
		return nil, fmt.Errorf("filter '%s' is invalid", filterName)
	}
good:

	in := service.cinp.ListObjects(ctx, "/api/v1/Proxmox/ProxmoxFoundation", reflect.TypeOf(ProxmoxProxmoxFoundation{}), filterName, filterValues, 50)
	out := make(chan *ProxmoxProxmoxFoundation)
	go func() {
		defer close(out)
		for v := range in {
			(*v).(*ProxmoxProxmoxFoundation).cinp = service.cinp
			out <- (*v).(*ProxmoxProxmoxFoundation)
		}
	}()
	return out, nil
}

func registerProxmox(cinp cinp.CInPClient) {
	cinp.RegisterType("/api/v1/Proxmox/ProxmoxComplex", reflect.TypeOf((*ProxmoxProxmoxComplex)(nil)).Elem())
	cinp.RegisterType("/api/v1/Proxmox/ProxmoxFoundation", reflect.TypeOf((*ProxmoxProxmoxFoundation)(nil)).Elem())
}
